[package]
name = "cogui"
version = "0.0.1"
edition = "2021"

[dependencies]
coren = { path = "../coren" }
# use this instead when compiling from github
#coren = { git = "https://github.com/Kono-o/coral-renderer.git" }
